repos:
  - repo: .
    rev: b2323c7d4aee770399418592a1a5ec790e00b968
    hooks:
      - id: conventional-msg
        name: conventional commit message
        entry: conventional-msg
        language: python
        stages: [commit-msg]
