repos:
  - repo: .
    rev: 50fd316f271eaf508d5787bd94d4c31e7329b699
    hooks:
      - id: conventional-msg
        name: conventional commit message
        entry: conventional-msg
        language: python
        stages: [commit-msg]
  - repo: local
    hooks:
    - id: pytest
      name: pytest
      entry: .venv/bin/pytest
      language: script
      pass_filenames: false
      always_run: true
      stages: [pre-commit]
