repos:
  - repo: .
    rev: ecec5cbd5f5f26350a64fa962cdd8cf1e6940850
    hooks:
      - id: conventional-msg
        name: conventional commit message
        entry: conventional-msg
        language: python
        stages: [commit-msg]
